// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtrb3LjmHwi27w02xIM-MuZ5wkOD-kALs',
    appId: '1:78618419171:web:f8d17af0c5c38136e30ad6',
    messagingSenderId: '78618419171',
    projectId: 'redditclone-2678b',
    authDomain: 'redditclone-2678b.firebaseapp.com',
    storageBucket: 'redditclone-2678b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9H1U04GLf9S0cNTN9pJAwm_D4hqkc09A',
    appId: '1:78618419171:android:da7980ee5828ffdfe30ad6',
    messagingSenderId: '78618419171',
    projectId: 'redditclone-2678b',
    storageBucket: 'redditclone-2678b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyKJ5qlYjTKseX47lxojjgcs89yczTIfI',
    appId: '1:78618419171:ios:802886c31bfad1b6e30ad6',
    messagingSenderId: '78618419171',
    projectId: 'redditclone-2678b',
    storageBucket: 'redditclone-2678b.appspot.com',
    androidClientId: '78618419171-d4hfl4fjha9eomr5e1snsg4ri98fcac5.apps.googleusercontent.com',
    iosClientId: '78618419171-7g2l68cnuslsiduvvl14pad90q7i8sek.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
